### ISSUE TITLE
` ``a+b'' ` does not decode correctly

### ISSUE THREAD

**Issue by davidweichiang** [mcmtroffaes/latexcodec#62]
This is the expected result:
```
>>> b"``a+b''".decode("latex")
'“a+b”'
```
But this is the actual result:
```
>>> b"``a+b''".decode("latex")
"“a+b''"
```
because the lexer makes `"+b''"` into a single token.

**Comment by mcmtroffaes** [comment]
This should now be fixed in develop, and will be included in the next release. Thanks again for reporting!

**Comment by davidweichiang** [comment]
Thank you! But won't this problem still occur with other characters, like ` ``a!b'' ``a(b)'' ``a=b'' ``a:b'' ``a;b'' ``a,b'' '' `?

It seems to me that the conundrum is the case at line 205 that handles multibyte characters. Do you envision this being used on encodings other than UTF-8? If you only needed to support UTF-8, then could lines 200 and 205 could be into a single regexp that grabs exactly one UTF-8 character?

If you need to support other encodings, would you consider it safe to make line 200 grab any byte between 00 and 7F, since in most multibyte encodings, these are single-byte characters?

Is there any possibility that when using the `ulatex` codec, this function could operate on Unicode strings instead of byte strings (and line 200 and 205 are merged into a single regexp that grabs exactly one character)?

Thanks again!

**Comment by mcmtroffaes** [comment]
Aye... I think it may be easiest to have 00-7F as separate tokens, and to bundle everything else together. The codec is definitely meant to support all encodings (as does TeX, with the right packages).

**Comment by mcmtroffaes** [comment]
@davidweichiang What do you think of this solution? https://github.com/mcmtroffaes/latexcodec/commit/e575ca3047131ea513c8ad30980d8b06d0c66705

**Comment by davidweichiang** [comment]
Thanks very much -- for me, that would be an improvement, though I imagine there are still going to be edge cases, like ` ``á'' `?

**Comment by mcmtroffaes** [comment]
I think https://github.com/mcmtroffaes/latexcodec/commit/ba4969e6b66dd9a63a4e2ef76a8360630f6824f0 should permanently fix this, and will at least allow unicode to be fully parsed correctly. Other encodings may break... I don't think that can be fixed easily, unfortunately. Anyway, does this fix the issue entirely for you?

In retrospect, rather than having two lexers for binary and unicode cases, it might be better just to leave the user to convert their text to unicode (using whichever encoding they want), and then have the lexer simply operate on the unicode directly.

**Comment by davidweichiang** [comment]
That works for me, thanks! But, would it also work more generally to decode bytes using `inputenc` _before_ lexing?

**Comment by mcmtroffaes** [comment]
Basically, yes. I'll close this since the original issue is fixed. That said, I'm still thinking to address this more coherently as suggested at a future time, to ensure all encodings work properly.
